### ISSUE TITLE
combine isoline and axis geoms

### ISSUE THREAD

**Issue by corybrunson** [corybrunson/ordr#39]
Currently, several geoms must be combined to form annotated isolines and annotated axes. As mentioned [here](https://github.com/corybrunson/ordr/issues/38#issuecomment-907802453), this can make a single plot a pain to layer. Ideally, these should be created by a single geom each. Since they involve elements of the same type (e.g. axes and tick marks) that may require different aesthetics (e.g. dashed and solid), additional aesthetics or parameters will be needed. There should be plenty of examples of how to do this effectively in other **ggplot2** extensions.

**Comment by jtr13** [comment]
At least from a user perspective (if not a technical one) it seems very similar to a **ggplot2** scales function... maybe `+ scale_rows(subset = ...)` with `name =`, `labels =`, `breaks = `, and other relevant parameters from the `scale_` functions.

**Comment by corybrunson** [comment]
@jtr13 that's definitely right from the user perspective. I looked into this possibility a while back, and i think the right way to think about it is that, while we may _read_ the variable axes of a biplot as we do the coordinate axes of a scatterplot, their _role_ is that of graphical elements of the plot rather than the coordinate scales with respect to which the graphical elements are rendered. This is a mechanical constraint of the `Scale*` (and `Coord*`) ggproto objects in **ggplot2**, but even in theory it is necessary because biplots usually only approximate the relationships between the case markers and the variable axes.

That said, it might make sense to adapt some of the `scale_*` parameters in addition to the aesthetic parameters from other complicated plot layers. Thank you for suggesting it!

**Comment by jtr13** [comment]
That makes sense, I appreciate the explanation!

**Comment by corybrunson** [comment]
Resolved as of 7ae7345164d3eee9544b04e9cefd3ec0be763bed. (But do raise future issues if functionality fails!)
